### ISSUE TITLE
Update tc-core-library-js version

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/legacy-challenge-resource-processor#1]
Upgrade to https://github.com/appirio-tech/tc-core-library-js/releases/tag/v2.6.2

**Comment by rootelement** [comment]
@ThomasKranitsas this is a very old issue. The version currently used is:
`"tc-core-library-js": "git+https://github.com/appirio-tech/tc-core-library-js.git#v2.6.2",`

Closing this. Reopen if I'm incorrect.
