### ISSUE TITLE
Member is not added as Submitter resource until Registration phase is open

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/legacy-challenge-resource-processor#12]
As per flow suggested [here](https://github.com/topcoder-platform/legacy-challenge-processor/issues/24#issuecomment-689487994) we are trying to add the assigned user of a task as `Submitter` role to the challenge but legacy resource processor is not able to add it to the legacy apps because the v4 api is throwing an error complaining that we can not add a resource in `Submitter` role until challenge is in registration phase.
So, we might have to skip using v4 api to add submitter resource for a task.

**Comment by vikasrohit** [comment]
fyi @rootelement @ThomasKranitsas

**Comment by lakshmiathreya** [comment]
@vikasrohit could this be closed pls?

**Comment by vikasrohit** [comment]
Yep, this one works fine now.
